# Site settings
title: 앳된 코더
description: 앳된 코더의 앳코더 잡기
permalink: ':title:output_ext'
baseurl: "/qgasdg.github.io" # the subpath of your site, e.g. /blog
url: "https://qgasdg.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/MVM-logo-full.svg"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/MVM-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Im Yun Taek # add your name
author-pic: Myself_Neon_grey.jpg
about-author: 인공지능학과 군휴학생

# Contact links
email: dbsxor0802@naver.com # Add your Email address
phone: # Add your Phone number
website: https://qgasdg.github.io # Add your website
linkedin: # Add your Linkedin handle
github: qgasdg # Add your Github handle
twitter:  # Add your Twitter handle
bandcamp:  # Add your Bandcamp username
stackoverflow: qgasdg # Add your stackoverflow account

# Newsletter
mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Tracker
analytics:
fbadmin: 

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: @disqus_TZQ1XMoqdP # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]